import numpy as np
from pyunicorn.eventseries import EventSeries as EV


def build_event_series(event_array: np.ndarray, taumax: int = 5) -> EV:
    """Wrap a binary event matrix in a pyunicorn ``EventSeries`` object.

    Parameters
    ----------
    event_array:
        2-D binary array of shape ``(time_steps, n_cells)``.
    taumax:
        Maximum lag (in time steps) for the Event Synchronization measure.
    """
    return EV(event_array, taumax=taumax)


def compute_significance(
    ev: EV,
    n_surr: int,
    symmetrization: str = "symmetric",
) -> np.ndarray:
    """Run a Monte Carlo surrogate significance test for Event Synchronization.

    Each surrogate is generated by randomising the event series; the returned
    matrix counts how many surrogates exceeded the observed ES score for each
    pair of cells.  Intended to be run on a cluster due to high compute cost.

    Parameters
    ----------
    ev:
        Fitted ``EventSeries`` object.
    n_surr:
        Number of surrogate realisations.
    symmetrization:
        ``"symmetric"`` for undirected, ``"directed"`` for directed analysis.

    Returns
    -------
    np.ndarray
        Integer matrix of shape ``(n_cells, n_cells)`` with surrogate counts.
    """
    n_cells = ev.get_event_matrix().shape[1]
    counts = np.zeros((n_cells, n_cells), dtype=np.int16)
    for _ in range(n_surr):
        result = ev.event_analysis_significance(
            method="ES", n_surr=1, symmetrization=symmetrization
        )
        counts += result.round().astype(np.int16)
    return counts


def build_adjacency_matrix(
    monte_carlo_counts: np.ndarray,
    n_surr: int,
    significance_level: float = 0.95,
) -> np.ndarray:
    """Threshold the Monte Carlo count matrix into a binary adjacency matrix.

    An edge (i, j) is retained when the observed ES exceeds more than
    ``significance_level * n_surr`` surrogates, i.e. the pair is significant
    at the ``significance_level`` confidence level.

    Parameters
    ----------
    monte_carlo_counts:
        Integer matrix returned by :func:`compute_significance`.
    n_surr:
        Total number of surrogates used (must match the value passed to
        :func:`compute_significance`).
    significance_level:
        Confidence threshold in ``(0, 1)``.
    """
    threshold = int(n_surr * significance_level)
    return np.where(monte_carlo_counts > threshold, 1, 0)
